### ISSUE TITLE
[Feature Request] add support for multiline selecting

### ISSUE THREAD

**Issue by GreenLim** [BaderEddineOuaich/flutter_syntax_view#7]
Awesome package!

It would be great to make the widget multiline selectable.

**Comment by BaderEddineOuaich** [comment]
Hello GreenLim, thanks for opening this issue.
I'm afraid this is not one of the library's goals. the main goal was to create a 'static syntax view'.
I would recommend other dynamic syntax highlighting widgets such as [code_editor](https://github.com/CodoPixel/code_editor) ...
