### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by bernaferrari** [BaderEddineOuaich/flutter_syntax_view#9]
I guess you already know about it, but there is no issue (yet), so I'm adding my own.

I would love to see this package being migrated.

**Comment by limcheekin** [comment]
First of all, thanks for your kindness of published the package. May I know do you have any plan on this matter?

I'm the creator of Flutter Widgets Explorer, I showcase the syntax_view package in the app, please see the following blog posts:
http://limcheekin.blogspot.com/2021/02/flutter-widgets-explorer-syntax-viewer.html
http://limcheekin.blogspot.com/2021/03/flutter-widgets-explorer-source-code.html

Also, the SyntaxView widget is in the "Code" tab of the ShowcaseView widget:
https://github.com/limcheekin/flutter-widgets-explorer/blob/main/showcase_view/README.md

I think you can imagine that the SyntaxView widget will be integrated into all showcases of the Flutter Widgets Explorer in coming weeks. In fact, 5 modules is integrated so far and 9 more to go.

After the integration completed, I will work on null safety next.

**Comment by BaderEddineOuaich** [comment]
Hello @bernaferrari and @limcheekin, thank you guys for opening this feature issue.
i have tried to migrate to null safety asap so you guys can keep working on your awesome projects!
now version 4.0.0 is migrated to null safety, please check change logs for breaking changes.
Thank you!

**Comment by bernaferrari** [comment]
That was fast, thanks a lot!!

**Comment by limcheekin** [comment]
Great! That's real quick! :)
